"use client";

// import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import ParentComponent from "@/component/parent";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="content">
          <ParentComponent />

          {/* <div className="flex-1">{children}</div> */}
        </div>
      </body>
    </html>
  );
}
